// Code generated by gobind. DO NOT EDIT.

// Java class mobileproxy.Proxy is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/Jigsaw-Code/outline-sdk/x/mobileproxy
package mobileproxy;

import go.Seq;

/**
 * Proxy enables you to get the actual address bound by the server and stop the service when no longer needed.
 */
public final class Proxy implements Seq.Proxy {
	static { Mobileproxy.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	Proxy(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public Proxy() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	/**
	 * AddURLProxy sets up a URL-based proxy handler that activates when an incoming HTTP request matches
	the specified path prefix. The pattern must represent a path segment, which is checked against
	the path of the incoming request.
	
	This function is particularly useful for libraries or components that accept URLs but do not support proxy
	configuration directly. By leveraging AddURLProxy, such components can route requests through a proxy by
	constructing URLs in the format &#34;http://${HOST}:${PORT}/${PATH}/${URL}&#34;, where &#34;${URL}&#34; is the target resource.
	For instance, using &#34;http://localhost:8080/proxy/https://example.com&#34; routes the request for &#34;https://example.com&#34;
	through a proxy at &#34;http://localhost:8080/proxy&#34;.
	
	The path should start with a forward slash (&#39;/&#39;) for clarity, but one will be added if missing.
	
	The function associates the given &#39;dialer&#39; with the specified &#39;path&#39;, allowing different dialers to be used for
	different path-based proxies within the same application in the future. currently we only support one URL proxy.
	 */
	public native void addURLProxy(String path, StreamDialer dialer);
	/**
	 * Address returns the IP and port the server is bound to.
	 */
	public native String address();
	/**
	 * Host returns the IP the server is bound to.
	 */
	public native String host();
	/**
	 * Port returns the port the server is bound to.
	 */
	public native long port();
	/**
	 * Stop gracefully stops the proxy service, waiting for at most timeout seconds before forcefully closing it.
	The function takes a timeoutSeconds number instead of a [time.Duration] so it&#39;s compatible with Go Mobile.
	 */
	public native void stop(long timeoutSeconds);
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof Proxy)) {
		    return false;
		}
		Proxy that = (Proxy)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("Proxy").append("{");
		return b.append("}").toString();
	}
}

