package R2;

import android.content.Context;
import com.google.android.gms.internal.measurement.B2;
import com.google.android.gms.internal.measurement.P2;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public abstract class K
{
  public static final P1 A;
  public static final P1 A0;
  public static final P1 B;
  public static final P1 B0;
  public static final P1 C;
  public static final P1 C0;
  public static final P1 D;
  public static final P1 D0;
  public static final P1 E;
  public static final P1 E0;
  public static final P1 F;
  public static final P1 F0;
  public static final P1 G;
  public static final P1 G0;
  public static final P1 H;
  public static final P1 H0;
  public static final P1 I;
  public static final P1 I0;
  public static final P1 J;
  public static final P1 J0;
  public static final P1 K;
  public static final P1 K0;
  public static final P1 L;
  public static final P1 L0;
  public static final P1 M;
  public static final P1 M0;
  public static final P1 N;
  public static final P1 N0;
  public static final P1 O;
  public static final P1 O0;
  public static final P1 P;
  public static final P1 P0;
  public static final P1 Q;
  public static final P1 Q0;
  public static final P1 R;
  public static final P1 R0;
  public static final P1 S;
  public static final P1 S0;
  public static final P1 T;
  public static final P1 T0;
  public static final P1 U;
  public static final P1 U0;
  public static final P1 V;
  public static final P1 V0;
  public static final P1 W;
  public static final P1 W0;
  public static final P1 X;
  public static final P1 X0;
  public static final P1 Y;
  public static final P1 Y0;
  public static final P1 Z;
  public static final P1 Z0;
  public static final List a = Collections.synchronizedList(new ArrayList());
  public static final P1 a0;
  public static final P1 a1;
  public static final Set b = Collections.synchronizedSet(new HashSet());
  public static final P1 b0;
  public static P1 b1;
  public static final P1 c;
  public static final P1 c0;
  public static final P1 d;
  public static final P1 d0;
  public static final P1 e;
  public static final P1 e0;
  public static final P1 f;
  public static final P1 f0;
  public static final P1 g;
  public static final P1 g0;
  public static final P1 h;
  public static final P1 h0;
  public static final P1 i;
  public static final P1 i0;
  public static final P1 j;
  public static final P1 j0;
  public static final P1 k;
  public static final P1 k0;
  public static final P1 l;
  public static final P1 l0;
  public static final P1 m;
  public static final P1 m0;
  public static final P1 n;
  public static final P1 n0;
  public static final P1 o;
  public static final P1 o0;
  public static final P1 p;
  public static final P1 p0;
  public static final P1 q;
  public static final P1 q0;
  public static final P1 r;
  public static final P1 r0;
  public static final P1 s;
  public static final P1 s0;
  public static final P1 t;
  public static final P1 t0;
  public static final P1 u;
  public static final P1 u0;
  public static final P1 v;
  public static final P1 v0;
  public static final P1 w;
  public static final P1 w0;
  public static final P1 x;
  public static final P1 x0;
  public static final P1 y;
  public static final P1 y0;
  public static final P1 z;
  public static final P1 z0;
  
  static
  {
    Object localObject1 = Long.valueOf(10000L);
    c = a("measurement.ad_id_cache_time", localObject1, localObject1, M.a);
    Object localObject2 = Long.valueOf(3600000L);
    d = a("measurement.app_uninstalled_additional_ad_id_cache_time", localObject2, localObject2, Q.a);
    Object localObject3 = Long.valueOf(86400000L);
    e = a("measurement.monitoring.sample_period_millis", localObject3, localObject3, e0.a);
    f = a("measurement.config.cache_time", localObject3, localObject2, q0.a);
    g = a("measurement.config.url_scheme", "https", "https", C0.a);
    h = a("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", P0.a);
    Object localObject4 = Integer.valueOf(100);
    i = a("measurement.upload.max_bundles", localObject4, localObject4, b1.a);
    Object localObject5 = Integer.valueOf(65536);
    j = a("measurement.upload.max_batch_size", localObject5, localObject5, o1.a);
    k = a("measurement.upload.max_bundle_size", localObject5, localObject5, A1.a);
    Integer localInteger = Integer.valueOf(1000);
    l = a("measurement.upload.max_events_per_bundle", localInteger, localInteger, O.a);
    localObject5 = Integer.valueOf(100000);
    m = a("measurement.upload.max_events_per_day", localObject5, localObject5, Z.a);
    n = a("measurement.upload.max_error_events_per_day", localInteger, localInteger, j0.a);
    localInteger = Integer.valueOf(50000);
    o = a("measurement.upload.max_public_events_per_day", localInteger, localInteger, w0.a);
    localInteger = Integer.valueOf(10000);
    p = a("measurement.upload.max_conversions_per_day", localInteger, localInteger, G0.a);
    localInteger = Integer.valueOf(10);
    q = a("measurement.upload.max_realtime_events_per_day", localInteger, localInteger, T0.a);
    r = a("measurement.store.max_stored_events_per_app", localObject5, localObject5, c1.a);
    s = a("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", q1.a);
    localObject5 = Long.valueOf(43200000L);
    t = a("measurement.upload.backoff_period", localObject5, localObject5, z1.a);
    u = a("measurement.upload.window_interval", localObject2, localObject2, L.a);
    v = a("measurement.upload.interval", localObject2, localObject2, N.a);
    w = a("measurement.upload.realtime_upload_interval", localObject1, localObject1, P.a);
    localObject2 = Long.valueOf(1000L);
    x = a("measurement.upload.debug_upload_interval", localObject2, localObject2, T.a);
    localObject2 = Long.valueOf(500L);
    y = a("measurement.upload.minimum_delay", localObject2, localObject2, S.a);
    localObject2 = Long.valueOf(60000L);
    z = a("measurement.alarm_manager.minimum_interval", localObject2, localObject2, V.a);
    A = a("measurement.upload.stale_data_deletion_interval", localObject3, localObject3, U.a);
    localObject3 = Long.valueOf(604800000L);
    B = a("measurement.upload.refresh_blacklisted_config_interval", localObject3, localObject3, X.a);
    localObject2 = Long.valueOf(15000L);
    C = a("measurement.upload.initial_upload_delay_time", localObject2, localObject2, W.a);
    localObject2 = Long.valueOf(1800000L);
    D = a("measurement.upload.retry_time", localObject2, localObject2, Y.a);
    localObject2 = Integer.valueOf(6);
    E = a("measurement.upload.retry_count", localObject2, localObject2, b0.a);
    localObject2 = Long.valueOf(2419200000L);
    F = a("measurement.upload.max_queue_time", localObject2, localObject2, a0.a);
    localObject2 = Integer.valueOf(4);
    G = a("measurement.lifetimevalue.max_currency_tracked", localObject2, localObject2, c0.a);
    localObject2 = Integer.valueOf(200);
    H = a("measurement.audience.filter_result_max_count", localObject2, localObject2, g0.a);
    localObject2 = Integer.valueOf(25);
    I = a("measurement.upload.max_public_user_properties", localObject2, localObject2, null);
    localObject1 = Integer.valueOf(500);
    J = a("measurement.upload.max_event_name_cardinality", localObject1, localObject1, null);
    K = a("measurement.upload.max_public_event_params", localObject2, localObject2, null);
    localObject2 = Long.valueOf(5000L);
    L = a("measurement.service_client.idle_disconnect_millis", localObject2, localObject2, f0.a);
    localObject2 = Boolean.FALSE;
    M = a("measurement.test.boolean_flag", localObject2, localObject2, i0.a);
    N = a("measurement.test.string_flag", "---", "---", h0.a);
    localObject1 = Long.valueOf(-1L);
    O = a("measurement.test.long_flag", localObject1, localObject1, k0.a);
    localObject1 = Integer.valueOf(-2);
    P = a("measurement.test.int_flag", localObject1, localObject1, m0.a);
    localObject1 = Double.valueOf(-3.0D);
    Q = a("measurement.test.double_flag", localObject1, localObject1, l0.a);
    localObject1 = Integer.valueOf(50);
    R = a("measurement.experiment.max_ids", localObject1, localObject1, o0.a);
    localObject1 = Integer.valueOf(27);
    S = a("measurement.upload.max_item_scoped_custom_parameters", localObject1, localObject1, n0.a);
    T = a("measurement.upload.max_event_parameter_value_length", localObject4, localObject4, p0.a);
    U = a("measurement.max_bundles_per_iteration", localObject4, localObject4, s0.a);
    V = a("measurement.sdk.attribution.cache.ttl", localObject3, localObject3, r0.a);
    localObject4 = Long.valueOf(7200000L);
    W = a("measurement.redaction.app_instance_id.ttl", localObject4, localObject4, u0.a);
    localObject4 = Integer.valueOf(7);
    X = a("measurement.rb.attribution.client.min_ad_services_version", localObject4, localObject4, t0.a);
    Y = a("measurement.rb.attribution.uri_scheme", "https", "https", v0.a);
    Z = a("measurement.rb.attribution.uri_authority", "google-analytics.com", "google-analytics.com", y0.a);
    a0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", "privacy-sandbox/register-app-conversion", x0.a);
    b0 = a("measurement.rb.attribution.app_allowlist", "com.labpixies.flood,", "com.labpixies.flood,", A0.a);
    c0 = a("measurement.rb.attribution.user_properties", "_npa,npa", "_npa,npa", z0.a);
    d0 = a("measurement.rb.attribution.event_params", "value|currency", "value|currency", B0.a);
    e0 = a("measurement.rb.attribution.query_parameters_to_remove", "", "", F0.a);
    localObject3 = Boolean.TRUE;
    f0 = a("measurement.collection.log_event_and_bundle_v2", localObject3, localObject3, D0.a);
    g0 = a("measurement.quality.checksum", localObject2, localObject2, null);
    h0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", localObject2, localObject2, H0.a);
    i0 = a("measurement.audience.refresh_event_count_filters_timestamp", localObject2, localObject2, J0.a);
    j0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", localObject2, localObject2, I0.a);
    k0 = a("measurement.sdk.collection.retrieve_deeplink_from_bow_2", localObject3, localObject3, L0.a);
    l0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", localObject2, localObject2, K0.a);
    m0 = a("measurement.lifecycle.app_in_background_parameter", localObject2, localObject2, N0.a);
    n0 = a("measurement.integration.disable_firebase_instance_id", localObject2, localObject2, M0.a);
    o0 = a("measurement.collection.service.update_with_analytics_fix", localObject2, localObject2, O0.a);
    p0 = a("measurement.client.firebase_feature_rollout.v1.enable", localObject3, localObject3, R0.a);
    q0 = a("measurement.client.sessions.check_on_reset_and_enable2", localObject3, localObject3, Q0.a);
    localObject4 = Integer.valueOf(203600);
    r0 = a("measurement.service.storage_consent_support_version", localObject4, localObject4, S0.a);
    s0 = a("measurement.client.click_identifier_control.dev", localObject2, localObject2, V0.a);
    t0 = a("measurement.service.click_identifier_control", localObject2, localObject2, U0.a);
    u0 = a("measurement.service.store_null_safelist", localObject3, localObject3, X0.a);
    v0 = a("measurement.service.store_safelist", localObject3, localObject3, W0.a);
    w0 = a("measurement.collection.enable_session_stitching_token.first_open_fix", localObject3, localObject3, Z0.a);
    x0 = a("measurement.collection.enable_session_stitching_token.client.dev", localObject3, localObject3, Y0.a);
    y0 = a("measurement.session_stitching_token_enabled", localObject2, localObject2, a1.a);
    z0 = a("measurement.sgtm.client.dev", localObject2, localObject2, d1.a);
    A0 = a("measurement.sgtm.service", localObject2, localObject2, g1.a);
    B0 = a("measurement.redaction.retain_major_os_version", localObject3, localObject3, e1.a);
    C0 = a("measurement.redaction.scion_payload_generator", localObject3, localObject3, i1.a);
    D0 = a("measurement.sessionid.enable_client_session_id", localObject3, localObject3, h1.a);
    E0 = a("measurement.sfmc.client", localObject3, localObject3, k1.a);
    F0 = a("measurement.sfmc.service", localObject3, localObject3, j1.a);
    G0 = a("measurement.gmscore_feature_tracking", localObject3, localObject3, m1.a);
    H0 = a("measurement.fix_health_monitor_stack_trace", localObject3, localObject3, l1.a);
    I0 = a("measurement.item_scoped_custom_parameters.client", localObject3, localObject3, n1.a);
    J0 = a("measurement.item_scoped_custom_parameters.service", localObject2, localObject2, p1.a);
    K0 = a("measurement.remove_app_background.client", localObject2, localObject2, s1.a);
    L0 = a("measurement.rb.attribution.service", localObject2, localObject2, r1.a);
    M0 = a("measurement.rb.attribution.client2", localObject2, localObject2, u1.a);
    N0 = a("measurement.rb.attribution.uuid_generation", localObject3, localObject3, t1.a);
    O0 = a("measurement.rb.attribution.enable_trigger_redaction", localObject3, localObject3, w1.a);
    P0 = a("measurement.rb.attribution.followup1.service", localObject2, localObject2, v1.a);
    Q0 = a("measurement.client.sessions.enable_fix_background_engagement", localObject2, localObject2, y1.a);
    R0 = a("measurement.client.ad_id_consent_fix", localObject3, localObject3, x1.a);
    S0 = a("measurement.dma_consent.client", localObject2, localObject2, C1.a);
    T0 = a("measurement.dma_consent.service", localObject2, localObject2, B1.a);
    U0 = a("measurement.dma_consent.client_bow_check", localObject2, localObject2, E1.a);
    V0 = a("measurement.dma_consent.service_gcs_v2", localObject2, localObject2, D1.a);
    W0 = a("measurement.dma_consent.service_npa_remote_default", localObject2, localObject2, H1.a);
    X0 = a("measurement.dma_consent.service_split_batch_on_consent", localObject2, localObject2, F1.a);
    Y0 = a("measurement.service.deferred_first_open", localObject2, localObject2, J1.a);
    Z0 = a("measurement.gbraid_campaign.gbraid.client.dev", localObject2, localObject2, I1.a);
    a1 = a("measurement.gbraid_campaign.gbraid.service", localObject2, localObject2, L1.a);
    b1 = a("measurement.increase_param_lengths", localObject2, localObject2, K1.a);
  }
  
  public static P1 a(String paramString, Object paramObject1, Object paramObject2, N1 paramN1)
  {
    paramString = new P1(paramString, paramObject1, paramObject2, paramN1, null);
    a.add(paramString);
    return paramString;
  }
  
  public static Map c(Context paramContext)
  {
    paramContext = B2.a(paramContext.getContentResolver(), P2.a("com.google.android.gms.measurement"), J.o);
    if (paramContext == null) {
      return Collections.emptyMap();
    }
    return paramContext.b();
  }
}

/* Location:
 * Qualified Name:     R2.K
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */